sudo: required
language: node_js
services:
- docker

env:
  global:
  - APP_PORT=80
  - DOCKER_IMAGE_NAME=$TRAVIS_REPO_SLUG:$TRAVIS_COMMIT
before_install:
- cd ./app
install:
- npm install -s
- npm run -s build
script:
- npm run -s lint
- npm run -s test-coverage
- cd ../ && docker build -t $DOCKER_IMAGE_NAME . && echo "built $DOCKER_IMAGE_NAME" && cd ./app
after_success:
- npm run -s coveralls-coverage
