sudo: required
language: node_js
services:
- docker
node_js:
- 8

env:
  global:
  - APP_PORT=80
  - DOCKER_IMAGE_NAME=$TRAVIS_REPO_SLUG:$TRAVIS_COMMIT
  - NATS_HOST=localhost
  - NATS_PORT=4222
before_install:
- cd ./app
install:
- npm install -s
- npm run -s build
before_script:
- docker run -d -p 4222:4222 nats
- docker run -d -v `pwd`/test-fixtures/config.json:/tmp/config.json ihsw/sotah-server -config /tmp/config.json -nats_host localhost -nats_port 4222
script:
- npm run -s lint
- ./bin/run-tests-coverage
- cd ../ && docker build -t $DOCKER_IMAGE_NAME . && echo "built $DOCKER_IMAGE_NAME" && cd ./app
after_success:
- npm run -s coveralls-coverage
