sudo: required
language: node_js
services:
- docker
- postgresql
node_js:
- 9

env:
  global:
  - DOCKER_IMAGE_NAME=$TRAVIS_REPO_SLUG:$TRAVIS_COMMIT
  - NATS_HOST=localhost
  - NATS_PORT=4222
  - DB_HOST=localhost
  - TYPEORM_HOST=$DB_HOST
  - TYPEORM_MIGRATIONS=./dist/migrations
  - secure: hx40d0IHT8UfA1OUP1JbID1h9hpwQhlynwpzduv87pQJ87QMqK/L1xeCKGl6gFZItH+dIz/C+VaohR1xNBdXWdi6M4A0w6hYe1Xb/9SOnBRjGLI7Fy8oiFgYe/xQvb/zHgXNporTXPP6uiB1JA3B/iesJP4k0iwf7hM5v+hP21ckHbQxqWatEwlEFxx+bPz0+Si/iLWdlb2zEi8SEmLIJfQzfSefbsvZUrwQ7ib6F7e1rayg2eirK+oGarJbrasUVnWvzsRN9/4Gr40D441xWw1N9E2nBIVJaLv+cLfR39/rrvd2mNKXkBZ7xwq2ekAF2yfsAXl2Qleyxi81XRvvk17FkUJ3+wuGq/14dI5KmOiUF7Ls+SggnJTr612qquYNyK7qUvD9+yeGhX4cXlnKE0uPrlhDei3xWS+IpAuewirt3b5MzHmLKJ1CPqTiF+/kJKpEHCz6DBdy30y8xEJIO8INZYXnXy+tx7GdgM8ryfbe4cauPYM2GncAhIYa3ihAp8QY4cJ8Wd/yCboL3shGi7CKj3F0ZUpUeSS0OdLaLJU/iqYMw0EMyPALEI0v/UkRIZmC4vTr+rEW9OlM4svxHrb4Mvqu0P51VOUeMEPbqgh27WijUqqqFwO//K+PFlTc/VHs0lcR21j0aTLZAmQA6DZKlmBsHCQhKYgVhz3pXAk=

before_install:
- cd $TRAVIS_BUILD_DIR/.. && git clone https://github.com/ihsw/sotah-server.git
- cd $TRAVIS_BUILD_DIR/../sotah-server && docker build -t ihsw/sotah-server .
- cd $TRAVIS_BUILD_DIR/.. && git clone https://github.com/ihsw/sotah-infra.git
- cd $TRAVIS_BUILD_DIR/../sotah-infra && docker-compose up -d sotah-server-api sotah-server-live-auctions sotah-server-pricelist-histories
install:
- cd $TRAVIS_BUILD_DIR/app && npm install -s
script:
- npm run -s build
- npm run -s lint
- npm run -s migrate-up
- ./bin/run-tests-coverage && npm run -s coveralls-coverage
- npm run -s test-coverage-report
- cd $TRAVIS_BUILD_DIR/../sotah-infra && docker-compose stop
- cd $TRAVIS_BUILD_DIR && git clean -xfd && docker build -t $DOCKER_IMAGE_NAME .
