steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/api:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/api',
            '--cache-from', 'gcr.io/$PROJECT_ID/api:latest',
            '.'
        ]
images: [
    'gcr.io/$PROJECT_ID/api:latest'
]
