version: "2"

services:
  db:
    image: postgres
  nats:
    image: nats
    ports:
    - "4222:4222"

  sotah-server-base:
    image: ihsw/sotah-server
    volumes:
    - ./sotah-server:/tmp/sotah-server
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug api
    environment:
    - API_KEY=$API_KEY
    - NATS_HOST=nats
  sotah-server:
    extends: sotah-server-base
    depends_on:
    - nats
  sotah-server-test:
    extends: sotah-server-base
    depends_on:
    - nats
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug api-test -d /tmp/sotah-server/test-fixtures

  sotah-api-base:
    build: .
    ports:
    - "8080:8080"
    environment:
    - NATS_HOST=nats
    - NATS_PORT=4222
    - DB_HOST=db
    volumes:
    - ./app:/srv/app
  sotah-api:
    extends: sotah-api-base
    depends_on:
    - sotah-server
    - nats
    - db
  sotah-api-test:
    extends: sotah-api-base
    depends_on:
    - sotah-server-test
    - nats
    - db
