version: "3"

services:
  nats:
    image: nats
    ports:
    - "4222:4222"
  sotah-server:
    image: ihsw/sotah-server
    depends_on:
    - nats
    volumes:
    - ./app/test-fixtures/config.json:/tmp/config.json
    command: -c /tmp/config.json -h nats
    environment:
    - API_KEY=$API_KEY
  sotah-api:
    build: .
    depends_on:
    - sotah-server