version: "2"

services:
  nats:
    image: nats
    ports:
    - "4222:4222"
  sotah-server:
    image: ihsw/sotah-server
    depends_on:
    - nats
    volumes:
    - ./app/test-fixtures:/tmp/fixtures
    command: -c /tmp/fixtures/config.json -v debug api-test -d /tmp/fixtures
    environment:
    - API_KEY=$API_KEY
    - NATS_HOST=nats
  sotah-api:
    build: .
    depends_on:
    - sotah-server
    - nats
    environment:
    - NATS_HOST=nats
    - NATS_PORT=4222
    volumes:
    - ./app:/srv/app
