version: "3"

services:
  nats:
    image: nats
    ports:
    - "4222:4222"
  sotah-server:
    image: ihsw/sotah-server
    depends_on:
    - nats
    volumes:
    - ./app/test-fixtures/config.json:/tmp/config.json
    command: -config /tmp/config.json -nats_host nats -p 4222
  sotah-api:
    build: .
    depends_on:
    - sotah-server