version: "2"

services:
  db:
    image: postgres
  nats:
    image: nats
    ports:
    - "4222:4222"


  sotah-server-base:
    image: ihsw/sotah-server
    volumes:
    - ./sotah-server:/tmp/sotah-server
    environment:
    - API_KEY=$API_KEY
    - NATS_HOST=nats
  
  sotah-server-live-auctions:
    extends: sotah-server-base
    depends_on:
    - nats
    - sotah-server-api
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug live-auctions

  sotah-server-api:
    extends: sotah-server-base
    depends_on:
    - nats
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug api
    volumes:
    - ./sotah-server/data/item-icons:/tmp/item-icons
  sotah-server-api-test:
    extends: sotah-server-base
    depends_on:
    - nats
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug api-test -d /tmp/sotah-server/test-fixtures

  sotah-server-sync-items:
    extends: sotah-server-base
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcloud-app-credentials.json
    - PROJECT_ID=$PROJECT_ID
    volumes:
    - $GOOGLE_APPLICATION_CREDENTIALS:/tmp/gcloud-app-credentials.json
    command: -c /tmp/sotah-server/config.json --cache-dir /tmp/sotah-server/data -v debug sync-items


  sotah-api-base:
    build: ./sotah-api
    ports:
    - "8080:8080"
    environment:
    - NATS_HOST=nats
    - NATS_PORT=4222
    - DB_HOST=db
  sotah-api:
    extends: sotah-api-base
    depends_on:
    - sotah-server-api
    - nats
    - db
    volumes:
    - ./sotah-api/app:/srv/app
    - ./sotah-server/data/item-icons:/tmp/item-icons
  sotah-api-test:
    extends: sotah-api-base
    depends_on:
    - sotah-server-api-test
    - nats
    - db
